import { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { Checkbox } from '@/components/ui/checkbox';
import { Loader2, Users, CheckCircle2, Plus, Tag } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { useQueryClient, useQuery } from '@tanstack/react-query';
import { useCrm } from '@/store/CrmContext';
import type { TriggerTag } from '@/types/bizdev';

const DEFAULT_TRIGGERS = [
  'New leadership',
  'Hiring surge',
  'Recent funding',
  'Expansion',
  'Renewal window',
  'Competitor movement',
];

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  selectedLeadIds: string[];
  onComplete: () => void;
}

export default function BulkCampaignModal({ open, onOpenChange, selectedLeadIds, onComplete }: Props) {
  const queryClient = useQueryClient();
  const { campaigns, addCampaign } = useCrm();
  const [mode, setMode] = useState<'select' | 'create'>('select');
  const [campaignId, setCampaignId] = useState('');
  const [processing, setProcessing] = useState(false);
  const [result, setResult] = useState<{ added: number } | null>(null);

  // New campaign fields
  const [newName, setNewName] = useState('');
  const [selectedTriggers, setSelectedTriggers] = useState<Set<string>>(new Set());
  const [customTrigger, setCustomTrigger] = useState('');
  const [customTriggers, setCustomTriggers] = useState<string[]>([]);

  // Load custom triggers from DB
  const { data: dbTriggers = [] } = useQuery({
    queryKey: ['trigger-dictionary'],
    queryFn: async () => {
      const { data } = await supabase.from('trigger_dictionary').select('label').eq('is_custom', true);
      return (data || []).map((t: any) => t.label as string);
    },
    enabled: open,
  });

  const allTriggerLabels = [...DEFAULT_TRIGGERS, ...dbTriggers.filter(t => !DEFAULT_TRIGGERS.includes(t)), ...customTriggers.filter(c => !DEFAULT_TRIGGERS.includes(c) && !dbTriggers.includes(c))];

  const toggleTrigger = (label: string) => {
    setSelectedTriggers(prev => {
      const next = new Set(prev);
      if (next.has(label)) next.delete(label);
      else next.add(label);
      return next;
    });
  };

  const addCustomTrigger = () => {
    const trimmed = customTrigger.trim();
    if (!trimmed || selectedTriggers.has(trimmed) || customTriggers.includes(trimmed)) return;
    setCustomTriggers(prev => [...prev, trimmed]);
    setSelectedTriggers(prev => new Set([...prev, trimmed]));
    setCustomTrigger('');
  };

  const handleAdd = async () => {
    let targetCampaignId = campaignId;

    // If creating a new campaign
    if (mode === 'create') {
      if (!newName.trim()) { toast.error('Enter a campaign name'); return; }
      const triggerTags: TriggerTag[] = Array.from(selectedTriggers).map(label => ({
        label,
        source: 'manual' as const,
        category: DEFAULT_TRIGGERS.includes(label) ? 'standard' : 'custom',
      }));

      // Save custom triggers to dictionary
      for (const label of selectedTriggers) {
        if (!DEFAULT_TRIGGERS.includes(label)) {
          await supabase.from('trigger_dictionary').upsert(
            { label, is_custom: true, created_by: 'user' } as any,
            { onConflict: 'label' }
          ).select();
        }
      }

      // Create campaign in CRM context
      addCampaign({
        name: newName.trim(),
        type: 'Custom',
        criteria: `Triggers: ${Array.from(selectedTriggers).join(', ')}`,
        industryTags: [],
        sizeTags: [],
        roleTags: Array.from(selectedTriggers),
        cadenceRules: 'LI touch then email 3 days later; advance weekly',
        weeklyPresets: Array.from({ length: 12 }, (_, i) => ({
          week: i + 1, emailTheme: '', linkedInTouch: '', cta: '', asset: '',
        })),
        active: true,
      });

      // The campaign ID is generated by CRM context — get it from the latest
      // We'll use the name for matching since we just added it
      targetCampaignId = newName.trim();
    } else {
      if (!targetCampaignId) { toast.error('Select a campaign'); return; }
    }

    setProcessing(true);
    try {
      const { data: leads } = await supabase.from('lead_queue').select('id, account_id').in('id', selectedLeadIds);
      if (!leads || leads.length === 0) { toast.error('No leads found'); setProcessing(false); return; }

      const accountIds = leads.map(l => l.account_id).filter(Boolean) as string[];

      const { data: contacts } = await supabase.from('contacts_le')
        .select('id, first_name, last_name, email, trigger_profile, campaign_batch_id, account_id')
        .in('account_id', accountIds);

      if (!contacts || contacts.length === 0) { toast.error('No contacts found for selected leads'); setProcessing(false); return; }

      const snapshots = contacts.map(c => ({
        account_id: c.account_id,
        contact_id: c.id,
        channel: 'campaign_membership',
        body: JSON.stringify({
          campaign_id: targetCampaignId,
          campaign_name: mode === 'create' ? newName.trim() : campaigns.find(c2 => c2.id === targetCampaignId)?.name,
          trigger_profile_snapshot: c.trigger_profile,
          campaign_batch_id: c.campaign_batch_id,
          triggers_selected: mode === 'create' ? Array.from(selectedTriggers) : [],
          added_at: new Date().toISOString(),
        }),
        week_number: 0,
        persona: null,
        industry_key: null,
      }));

      const { error } = await supabase.from('message_snapshots').insert(snapshots as any);
      if (error) throw error;

      await supabase.from('lead_queue')
        .update({ claim_status: 'in_campaign', status: 'in_campaign' } as any)
        .in('id', selectedLeadIds);

      setResult({ added: contacts.length });
      queryClient.invalidateQueries({ queryKey: ['lead-queue'] });
      toast.success(`${contacts.length} contacts added to campaign`);

      await supabase.from('audit_log').insert({
        actor: 'user', action: 'bulk_add_campaign', entity_type: 'contacts_le',
        details: { campaign_id: targetCampaignId, contacts: contacts.length, leads: selectedLeadIds.length },
      });
    } catch (err: any) {
      toast.error(`Failed: ${err.message}`);
    } finally {
      setProcessing(false);
    }
  };

  const handleClose = () => {
    setResult(null);
    setCampaignId('');
    setMode('select');
    setNewName('');
    setSelectedTriggers(new Set());
    setCustomTrigger('');
    setCustomTriggers([]);
    onOpenChange(false);
    if (result) onComplete();
  };

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="max-w-lg max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Users size={20} className="text-primary" /> Add to Campaign
          </DialogTitle>
        </DialogHeader>

        {result ? (
          <div className="text-center py-6 space-y-3">
            <CheckCircle2 size={40} className="mx-auto text-primary" />
            <p className="text-sm text-foreground font-medium">Added to campaign</p>
            <p className="text-xs text-muted-foreground">{result.added} contacts with trigger profiles preserved</p>
            <Button size="sm" onClick={handleClose}>Done</Button>
          </div>
        ) : (
          <div className="space-y-4">
            <p className="text-sm text-muted-foreground">
              Add <Badge variant="secondary" className="text-[10px]">{selectedLeadIds.length} leads</Badge> to a 12-week drip campaign.
            </p>

            {/* Mode toggle */}
            <div className="flex gap-2">
              <Button size="sm" variant={mode === 'select' ? 'default' : 'outline'} onClick={() => setMode('select')}>
                Select Existing
              </Button>
              <Button size="sm" variant={mode === 'create' ? 'default' : 'outline'} onClick={() => setMode('create')}>
                <Plus size={14} className="mr-1" /> Create New
              </Button>
            </div>

            {mode === 'select' ? (
              campaigns.length > 0 ? (
                <Select value={campaignId} onValueChange={setCampaignId}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select campaign…" />
                  </SelectTrigger>
                  <SelectContent>
                    {campaigns.map((c: any) => (
                      <SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              ) : (
                <div className="text-xs text-muted-foreground bg-muted/50 rounded p-3">
                  No campaigns yet. Switch to "Create New" to make one.
                </div>
              )
            ) : (
              <div className="space-y-4">
                <div>
                  <Label className="text-xs">Campaign Name *</Label>
                  <Input
                    value={newName}
                    onChange={e => setNewName(e.target.value)}
                    placeholder="e.g. Q1 Florida Tech 50-250"
                    className="mt-1"
                  />
                </div>

                {/* Trigger selection */}
                <div>
                  <div className="flex items-center gap-2 mb-2">
                    <Tag size={14} className="text-primary" />
                    <Label className="text-xs">Campaign Triggers</Label>
                    {selectedTriggers.size > 0 && (
                      <Badge variant="outline" className="text-[9px]">{selectedTriggers.size} selected</Badge>
                    )}
                  </div>
                  <div className="grid grid-cols-2 gap-1.5">
                    {allTriggerLabels.map(label => (
                      <label
                        key={label}
                        className="flex items-center gap-2 text-xs cursor-pointer hover:bg-muted/50 rounded px-2 py-1.5 transition-colors"
                      >
                        <Checkbox
                          checked={selectedTriggers.has(label)}
                          onCheckedChange={() => toggleTrigger(label)}
                        />
                        <span className="text-foreground">{label}</span>
                        {!DEFAULT_TRIGGERS.includes(label) && (
                          <Badge variant="secondary" className="text-[8px] ml-auto">custom</Badge>
                        )}
                      </label>
                    ))}
                  </div>
                  <div className="flex gap-2 mt-2">
                    <Input
                      value={customTrigger}
                      onChange={e => setCustomTrigger(e.target.value)}
                      placeholder="Add custom trigger…"
                      className="text-xs h-8"
                      onKeyDown={e => e.key === 'Enter' && (e.preventDefault(), addCustomTrigger())}
                    />
                    <Button size="sm" variant="outline" className="h-8" onClick={addCustomTrigger} disabled={!customTrigger.trim()}>
                      <Plus size={12} />
                    </Button>
                  </div>
                </div>
              </div>
            )}

            <div className="flex justify-end gap-2 pt-2">
              <Button variant="outline" size="sm" onClick={handleClose}>Cancel</Button>
              <Button size="sm" onClick={handleAdd} disabled={processing}>
                {processing ? <Loader2 size={14} className="mr-1 animate-spin" /> : null}
                {mode === 'create' ? 'Create & Add' : 'Add to Campaign'}
              </Button>
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
